import { format } from "date-fns"

import { clientDateFormat } from "@/lib/date-utils"

const buildDefaultGLJournalDetails = (_dateFormat: string) => ({
  journalId: "0",
  journalNo: "",
  itemNo: 0,
  seqNo: 0,
  productId: 0,
  productCode: "",
  productName: "",
  glId: 0,
  glCode: "",
  glName: "",
  remarks: "",
  isDebit: false,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstId: 1,
  gstName: "",
  gstPercentage: 0,
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  departmentId: 0,
  departmentCode: "",
  departmentName: "",
  employeeId: 0,
  employeeCode: "",
  employeeName: "",
  portId: 0,
  portCode: "",
  portName: "",
  vesselId: 0,
  vesselCode: "",
  vesselName: "",
  bargeId: 0,
  bargeCode: "",
  bargeName: "",
  voyageId: 0,
  voyageNo: "",
  jobOrderId: 0,
  jobOrderNo: "",
  taskId: 0,
  taskName: "",
  serviceItemNo: 0,
  serviceItemNoName: "",
  editVersion: 0,
})

const buildDefaultGLJournal = (dateFormat: string) => ({
  companyId: 0,
  journalId: "0",
  journalNo: "",
  referenceNo: "",
  trnDate: format(new Date(), dateFormat),
  accountDate: format(new Date(), dateFormat),
  currencyId: 0,
  exhRate: 0,
  ctyExhRate: 0,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstClaimDate: format(new Date(), dateFormat),
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  totAmtAftGst: 0,
  totLocalAmtAftGst: 0,
  totCtyAmtAftGst: 0,
  remarks: "",
  isReverse: false,
  isRecurrency: false,
  revDate: format(new Date(), dateFormat),
  recurrenceUntilDate: format(new Date(), dateFormat),
  moduleFrom: "",
  createById: 0,
  createDate: format(new Date(), dateFormat),
  editById: "",
  editDate: "",
  isCancel: false,
  cancelById: 0,
  cancelDate: "",
  cancelRemarks: "",
  createBy: "",
  editBy: "",
  cancelBy: "",
  editVersion: 0,
  isPost: false,
  postById: "",
  postDate: "",
  appStatusId: "",
  appById: "",
  appDate: "",
  data_details: [],
})

// Function to get default values with custom date format
export const getDefaultValues = (dateFormat: string = clientDateFormat) => ({
  defaultGLJournal: buildDefaultGLJournal(dateFormat),
  defaultGLJournalDetails: buildDefaultGLJournalDetails(dateFormat),
})

export const defaultGLJournal = buildDefaultGLJournal(clientDateFormat)
export const defaultGLJournalDetails =
  buildDefaultGLJournalDetails(clientDateFormat)
