import { format } from "date-fns"

import { clientDateFormat } from "@/lib/date-utils"

const buildDefaultInvoiceDetails = (dateFormat: string) => ({
  invoiceId: "0",
  invoiceNo: "",
  itemNo: 0,
  seqNo: 0,
  docItemNo: 0,
  productId: 0,
  productCode: "",
  productName: "",
  glId: 0,
  glCode: "",
  glName: "",
  qty: 0,
  billQTY: 0,
  uomId: 0,
  uomCode: "",
  uomName: "",
  unitPrice: 0,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  debitNoteNo: "",
  remarks: "",
  gstId: 0,
  gstName: "",
  gstPercentage: 0,
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  deliveryDate: format(new Date(), dateFormat),
  departmentId: 0,
  departmentCode: "",
  departmentName: "",
  employeeId: 0,
  employeeCode: "",
  employeeName: "",
  portId: 0,
  portCode: "",
  portName: "",
  vesselId: 0,
  vesselCode: "",
  vesselName: "",
  bargeId: 0,
  bargeCode: "",
  bargeName: "",
  voyageId: 0,
  voyageNo: "",
  operationId: "0",
  operationNo: "",
  opRefNo: "",
  salesOrderId: "0",
  salesOrderNo: "",
  supplyDate: format(new Date(), dateFormat),
  supplierName: "",
  suppInvoiceNo: "",
  apInvoiceId: "",
  apInvoiceNo: "",
  editVersion: 0,
})

const buildDefaultInvoice = (dateFormat: string) => ({
  companyId: 0,
  invoiceId: "0",
  invoiceNo: "",
  referenceNo: "",
  trnDate: format(new Date(), dateFormat),
  accountDate: format(new Date(), dateFormat),
  deliveryDate: format(new Date(), dateFormat),
  dueDate: format(new Date(), dateFormat),
  customerId: 0,
  currencyId: 0,
  exhRate: 0,
  ctyExhRate: 0,
  creditTermId: 0,
  bankId: 0,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstClaimDate: format(new Date(), dateFormat),
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  totAmtAftGst: 0,
  totLocalAmtAftGst: 0,
  totCtyAmtAftGst: 0,
  balAmt: 0,
  balLocalAmt: 0,
  payAmt: 0,
  payLocalAmt: 0,
  exGainLoss: 0,
  salesOrderId: 0,
  salesOrderNo: "",
  operationId: 0,
  operationNo: "",
  remarks: "",
  billName: "",
  address1: "",
  address2: "",
  address3: "",
  address4: "",
  addressId: 0,
  contactId: 0,
  pinCode: "",
  countryId: 0,
  phoneNo: "",
  faxNo: "",
  contactName: "",
  mobileNo: "",
  emailAdd: "",
  moduleFrom: "",
  supplierName: "",
  suppInvoiceNo: "",
  apInvoiceId: "0",
  apInvoiceNo: "",
  createById: 0,
  createDate: format(new Date(), dateFormat),
  editById: "",
  editDate: "",
  isCancel: false,
  cancelById: 0,
  cancelDate: "",
  cancelRemarks: "",
  createBy: "",
  editBy: "",
  cancelBy: "",
  editVersion: 0,
  isPost: false,
  postById: "",
  postDate: "",
  appStatusId: "",
  appById: "",
  appDate: "",
  jobOrderId: 0,
  jobOrderNo: "",
  vesselId: 0,
  portId: 0,
  serviceCategoryId: 0,
  otherRemarks: "",
  advRecAmt: 0,
  bargeId: 0,
  data_details: [],
})

// Function to get default values with custom date format
export const getDefaultValues = (dateFormat: string = clientDateFormat) => ({
  defaultInvoice: buildDefaultInvoice(dateFormat),
  defaultInvoiceDetails: buildDefaultInvoiceDetails(dateFormat),
})

export const defaultInvoice = buildDefaultInvoice(clientDateFormat)
export const defaultInvoiceDetails =
  buildDefaultInvoiceDetails(clientDateFormat)
