const defaultBankReconDetails = {
  reconId: "0",
  reconNo: "",
  itemNo: 0,
  isSel: false,
  moduleId: 0,
  transactionId: 0,
  documentId: 0,
  documentNo: "",
  docReferenceNo: "",
  accountDate: new Date(),
  paymentTypeId: 0,
  chequeNo: "",
  chequeDate: new Date(),
  customerId: 0,
  supplierId: 0,
  glId: 0,
  isDebit: false,
  exhRate: 0,
  totAmt: 0,
  totLocalAmt: 0,
  paymentFromTo: "",
  remarks: "",
  editVersion: 0,
}

const defaultBankRecon = {
  companyId: 0,
  reconId: "0",
  reconNo: "",
  prevReconId: 0,
  prevReconNo: "",
  referenceNo: "",
  trnDate: new Date(),
  accountDate: new Date(),
  bankId: 0,
  currencyId: 0,
  fromDate: new Date(),
  toDate: new Date(),
  remarks: "",
  totAmt: 0,
  opBalAmt: 0,
  clBalAmt: 0,
  createById: 0,
  createDate: new Date(),
  editById: undefined,
  editDate: undefined,
  editVersion: 0,
  isCancel: false,
  cancelById: undefined,
  cancelDate: undefined,
  cancelRemarks: undefined,
  isPost: false,
  postById: undefined,
  postDate: undefined,
  appStatusId: undefined,
  appById: undefined,
  appDate: undefined,
  data_details: [],
}

export { defaultBankRecon, defaultBankReconDetails }
