import { format } from "date-fns"

import { clientDateFormat } from "@/lib/date-utils"

const buildDefaultAdjustmentDetails = (dateFormat: string) => ({
  adjustmentId: "0",
  adjustmentNo: "",
  itemNo: 0,
  seqNo: 0,
  docItemNo: 0,
  productId: 0,
  productCode: "",
  productName: "",
  glId: 0,
  glCode: "",
  glName: "",
  qty: 0,
  billQTY: 0,
  uomId: 0,
  uomCode: "",
  uomName: "",
  unitPrice: 0,
  isDebit: false,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  remarks: "",
  gstId: 1,
  gstName: "",
  gstPercentage: 0,
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  deliveryDate: format(new Date(), dateFormat),
  departmentId: 0,
  departmentCode: "",
  departmentName: "",

  employeeId: 0,
  employeeCode: "",
  employeeName: "",
  portId: 0,
  portCode: "",
  portName: "",
  vesselId: 0,
  vesselCode: "",
  vesselName: "",
  bargeId: 0,
  bargeCode: "",
  bargeName: "",
  voyageId: 0,
  voyageNo: "",
  operationId: "0",
  operationNo: "",
  opRefNo: "",
  purchaseOrderId: "0",
  purchaseOrderNo: "",
  supplyDate: format(new Date(), dateFormat),
  customerName: "",
  custAdjustmentNo: "",
  arAdjustmentId: "",
  arAdjustmentNo: "",
  editVersion: 0,
})

const buildDefaultAdjustment = (dateFormat: string) => ({
  companyId: 0,
  adjustmentId: "0",
  adjustmentNo: "",
  referenceNo: "",
  suppAdjustmentNo: "",
  trnDate: format(new Date(), dateFormat),
  accountDate: format(new Date(), dateFormat),
  deliveryDate: format(new Date(), dateFormat),
  dueDate: format(new Date(), dateFormat),
  supplierId: 0,
  currencyId: 0,
  exhRate: 0,
  ctyExhRate: 0,
  creditTermId: 0,
  bankId: 0,
  isDebit: false,
  totAmt: 0,
  totLocalAmt: 0,
  totCtyAmt: 0,
  gstClaimDate: format(new Date(), dateFormat),
  gstAmt: 0,
  gstLocalAmt: 0,
  gstCtyAmt: 0,
  totAmtAftGst: 0,
  totLocalAmtAftGst: 0,
  totCtyAmtAftGst: 0,
  balAmt: 0,
  balLocalAmt: 0,
  payAmt: 0,
  payLocalAmt: 0,
  exGainLoss: 0,
  purchaseOrderId: 0,
  purchaseOrderNo: "",
  operationId: 0,
  operationNo: "",
  remarks: "",
  moduleFrom: "",
  customerName: "",
  custAdjustmentNo: "",
  arAdjustmentId: "0",
  arAdjustmentNo: "",
  createById: 0,
  createDate: format(new Date(), dateFormat),
  editById: "",
  editDate: "",
  isCancel: false,
  cancelById: 0,
  cancelDate: "",
  cancelRemarks: "",
  createBy: "",
  editBy: "",
  cancelBy: "",
  editVersion: 0,
  isPost: false,
  postById: "",
  postDate: "",
  appStatusId: "",
  appById: "",
  appDate: "",
  data_details: [],
})

// Function to get default values with custom date format
export const getDefaultValues = (dateFormat: string = clientDateFormat) => ({
  defaultAdjustment: buildDefaultAdjustment(dateFormat),
  defaultAdjustmentDetails: buildDefaultAdjustmentDetails(dateFormat),
})

export const defaultAdjustment = buildDefaultAdjustment(clientDateFormat)
export const defaultAdjustmentDetails =
  buildDefaultAdjustmentDetails(clientDateFormat)
