import { z } from "zod"

export const FreightSchema = z.object({
  consignmentImportId: z.number().optional(),
  companyId: z.number().min(1, "Company ID is required"),
  companyCode: z.string().optional(),
  jobOrderId: z.number().min(1, "Job Order ID is required"),
  jobOrderNo: z.string().optional(),
  referenceNo: z.string().optional(),
  vesselName: z.string().optional(),
  vesselId: z.number().min(1, "Vessel ID is required"),
  awbNo: z.string().optional(),
  declarationNo: z.string().optional(),
  billEntryNo: z.string().optional(),
  receiveDate: z.union([z.date(), z.string()]).nullable().optional(),
  arrivalDate: z.union([z.date(), z.string()]).nullable().optional(),
  noOfPcs: z.number().nullable().optional(),
  weight: z.number().nullable().optional(),
  clearedBy: z.string().optional(),
  amountDeposited: z.number().nullable().optional(),
  remarks: z.string().optional(),
  description: z.string().optional(),
  carrierId: z.number().nullable().optional(),
  carrierName: z.string().optional(),
  refundInstrumentNo: z.string().optional(),
  taskId: z.number().nullable().optional(),
  poNo: z.string().optional(),
  chargeId: z.number().min(1, "Charge is required"),
  chargeName: z.string().optional(),
  serviceModeId: z.number().nullable().optional(),
  serviceModeName: z.string().optional(),
  consignmentTypeId: z.number().nullable().optional(),
  consignmentTypeName: z.string().optional(),
  landingTypeId: z.number().nullable().optional(),
  landingTypeName: z.string().optional(),
  pickupLocation: z.string().optional(),
  deliveryLocation: z.string().optional(),
  deliverDate: z.union([z.date(), z.string()]).nullable().optional(),
  uomId: z.number().nullable().optional(),
  uomName: z.string().optional(),
  debitNoteId: z.number().nullable().optional(),
  debitNoteNo: z.string().optional(),
  taskStatusId: z.number().min(1, "Task Status is required"),
  taskStatusName: z.string().optional(),
  isCleared: z.boolean().optional(),
  existPortCustom: z.string().nullable().optional(),
  editVersion: z.number().optional(),
})

export type FreightSchemaType = z.infer<typeof FreightSchema>

